name: Deploy to packagecloud
on: [release]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        os:
          - OS=el DIST=6
          - OS=el DIST=7
          - OS=fedora DIST=26
          - OS=fedora DIST=27
          - OS=fedora DIST=28
          - OS=fedora DIST=29
        repository:
          - "1_10"
          - "2x"
          - "2_2"
          - "2_3"
          - "2_4"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: packpack
        run: |
          git clone https://github.com/packpack/packpack.git packpack
          ${{ matrix.os }} packpack/packpack
          ls -l build/

      - name: packagecloud
        uses: docker://lpenz/ghaction-packagecloud:v0.1
        with:
          user: tarantool
          repository: ${{ matrix.repository }}
          directory: build
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
