name: Tests
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "tarantool/tarantool:1.10.8"
          # - "tarantool/tarantool:2.2"
          # - "tarantool/tarantool:2.3"
          # - "tarantool/tarantool:2.4"
          # - "tarantool/tarantool:2.5"
          # - "tarantool/tarantool:2.6"
          # - "tarantool/tarantool:2.7.0"
        cartridge: [ '' ]
        # cartridge: [ '', "1.2.0", "2.1.2" ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
      env:
        CARTRIDGE_VERSION: ${{ matrix.cartridge }}
    steps:
      - uses: actions/checkout@v2

      - name: deps
        run: apk add --update alpine-sdk make curl git cmake gcc

      # - name: lint
      #   run: make lint

      # - name: test
      #   run: make test_with_coverage_report

  packpack:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        os:
          - OS=el DIST=6
          # - OS=el DIST=7
          # - OS=fedora DIST=26
          # - OS=fedora DIST=27
          # - OS=fedora DIST=28
          # - OS=fedora DIST=29
        repository:
          - "1_10"
          # - "2x"
          # - "2_2"
          # - "2_3"
          # - "2_4"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: deps
        run: |
          gem install package_cloud

      # - name: packpack
      #   run: |
      #     git clone https://github.com/packpack/packpack.git packpack
      #     ${{ matrix.os }} packpack/packpack
      #     ls -l build/

      # - name: packagecloud
      #   run: ${{ secrets.PACKAGECLOUD_TOKEN }} package_cloud push --verbose tarantool/${{ matrix.repository }} build/*.deb
        # env:
        #   PACKAGECLOUD_TOKEN:
